### ISSUE TITLE
Unable to set password

### ISSUE THREAD

**Issue by talesam** [joseluisq/static-web-server#109]
I created a test password with the apache command. Is there another way to create the password without depending on apache?

```
root@dd55d312d133:/# htpasswd -nbBC5 "user01" "teste123"
user01:$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK
```

```
container_name: sws-tt
    restart: always
    environment:
      - SERVER_DIRECTORY_LISTING=true
      - SERVER_BASIC_AUTH='user01:$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK'
      # Nota: esses envs são personalizáveis, mas também opcionais
```

```
ubuntu@vtrinity:~/Docker/SWS$ docker-compose ps
WARN[0000] The "IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK" variable is not set. Defaulting to a blank string. 
invalid interpolation format for services.sws-tt.environment.[]: "SERVER_BASIC_AUTH='user01:$$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK'". You may need to escape any $ with another $.
```

**Comment by joseluisq** [comment]
> I created a test password with the apache command. Is there another way to create the password without depending on apache?

You just need to wrap your env values around doble quotes.

```yml
- "SERVER_BASIC_AUTH=user01:$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK"
```

**Comment by talesam** [comment]
> 
Did not work
```
ubuntu@vtrinity:~/Docker/SWS$ docker-compose ps
WARN[0000] The "IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK" variable is not set. Defaulting to a blank string. 
invalid interpolation format for services.sws-tt.environment.[]: "SERVER_BASIC_AUTH=user01:$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK". You may need to escape any $ with another $.
```

**Comment by talesam** [comment]
The solution you sent didn't work, and you closed it here, I don't know if you will receive this message.

**Comment by joseluisq** [comment]
I just closed the issue because is not an SWS issue but a syntax error for your Docker/Yaml file.

Anyway, as far as I have seen you are facing _a variable substitution issue_ because of the dollar sign `$` in your file that you have not escaped.

> You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.
> https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution

So what you can do is something like this:

```yml
- "SERVER_BASIC_AUTH=user01:$$2y$05$$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK"
```

**Comment by talesam** [comment]
> I just closed the issue because is not an SWS issue but a syntax error for your Docker/Yaml file.
> 
> Anyway, as far as I have seen you are facing _a variable substitution issue_ because of the dollar sign `$` in your file that you have not escaped.
> 
> > You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.
> > https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution
> 
> So what you can do is something like this:
> 
> ```yaml
> - "SERVER_BASIC_AUTH=user01:$$2y$05$$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK"
> ```
Don´t Work

```
version: "3.9"

services:
  sws-tt:
    image: joseluisq/static-web-server:2
    container_name: sws-tt
    restart: always
    environment:
      - SERVER_DIRECTORY_LISTING=true
      - "SERVER_BASIC_AUTH=user01:$$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK"
      # Nota: esses envs são personalizáveis, mas também opcionais
      #- SERVER_HOST=127.0.0.1
      #- SERVER_PORT=80
      #- SERVER_ROOT=/public
    volumes:
      - /home/ubuntu/Docker/SWS/tt/html:/public
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.entryPoints=https"
    #  - "traefik.backend=localhost_dev"
    #  - "traefik.frontend.rule=Host:localhost.dev"
    #  - "traefik.port=80"
    ports:
      - 8080:80
    networks:
      sws-net:

networks:
  sws-net:
      name: sws-net
```

```
ubuntu@vtrinity:~/Docker/SWS$ docker-compose ps
WARN[0000] The "IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK" variable is not set. Defaulting to a blank string. 
invalid interpolation format for services.sws-tt.environment.[]: "SERVER_BASIC_AUTH=user01:$$2y$05$IAu7m5jhbpQqzSv1u7JjGO3MrkVMUXXGY7a245klF55gifHjMZpOK". You may need to escape any $ with another $.
```
