### ISSUE TITLE
Cache Issues

### ISSUE THREAD

**Issue by tuta-amb** [joseluisq/static-web-server#280]
I'm using this as a development server, however I'm running into the major issue that the files are being cached. I'm not sure exactly what is happening, but it seems like my linked JS Module files are being cached and the new versions are not being served. This is my configuration file:
```toml
[general]
port = 8080
host = "::"
root = "./src"
log-level = "trace"
cache-control-headers = false
compression = false
page404 = "./src/404.html"
page50x = "./src/500.html"
page-fallback = "./src/index.html"
directory-listing = true
log-remote-address = true
ignore-hidden-files = true
redirect-trailing-slash = true

[[advanced.headers]]
source = "*"
[advanced.headers.headers]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"
```
I've tried to add cache headers but the files are still not being updated. The only solution that I can use is to manually use my browser to visit the script file locations, which then updates the cache.
