### ISSUE TITLE
Configuration advanced.headers is not applied when html served though 'index-files' matching

### ISSUE THREAD

**Issue by fuweichin** [joseluisq/static-web-server#332]
### Search for duplicate issues

- [X] I already searched, and this issue is not a duplicate.

### Issue scope

Configuration (e.g. TOML)

### Describe the bug

As described by title, this seems to be a bug, as use of index file is so common. Nginx uses MIME type or scripting with `$request_filename` to match custom header rules, so it doesn't have such issue.

### How to reproduce it

1. Prepare configuration file config.toml.
```toml
# ...
directory-listing = true
index-files = "index.html"

[advanced]

[[advanced.headers]]
source = "**/*.{html,js,css,png,ico,json,xml}"
headers = { Cross-Origin-Embedder-Policy = "require-corp", Cross-Origin-Opener-Policy = "same-origin" }
```
2. Start server with command `static-web-server -w config.toml`.
3. Open a browser tab, access a directory which contains index.html, open another browser tab, access the previously matched index file with explicit path, e.g. "/index.html".
4. Compare response headers of the two requests, you may see the response of directory index-matching doesn't contain CORP headers.

### Expected behavior

When matching index files, actual requested file name SHOULD be used to match '[[advanced.headers]] souce' instead of the original request uri.

By the way, resources served though "directory-listing" MAY be assumed to have a default file name and an extension of the "directory-listing-format" option value, e.g. "directory-listing.html", thus to match rules in the "[[advanced.headers]]" section.

### Build target

x86_64-pc-windows-msvc

### Environment and specs

- [ ] **static-web-server:** 2.28.0
- [ ] **OS:** Windows 10
- [ ] **Arch:** x86_64 (64-bit)
- [ ] **Docker:**
- [ ] **Client:** Chrome 123
- [ ] Specify others
