### ISSUE TITLE
support base serving path

### ISSUE THREAD

**Issue by superwushu** [joseluisq/static-web-server#462]
### Search for duplicate feature request

- [X] I already searched, and this feature request or improvement is not a duplicate.

### Feature scope

Improve existing functionality

### Feature request related to a problem

We may want to serve the static files under a sub-path URL instead of the root URL. This may be helpful in cases only one host name is available but we need to serve multiple services.

### Describe the solution you'd like

A new`--base-path <base>` option or env variable to map all requests for `/<base>/...` to files under `<ROOT>/...`.

### Describe alternatives you've considered

Currently I use the rewrite rule in Nginx to workaroud this, by removing `/<path>/` before redirecting requests to SWS and by adding `/<path>/' for URLs in responses. This is ugly and error prone. It would be nice if SWS can natively support it.

### Build target

All targets

**Comment by joseluisq** [comment]
It would appreciate you sharing an example of what you think could work, maybe a couple of requests to help me to understand the feature better.

**Comment by joseluisq** [comment]
Maybe what you want is  [URL Rewrites](https://static-web-server.net/features/url-rewrites/)? If so then you can achieve it as follows.

For example, let's assume we want to serve two websites from the same root dir without exposing the internal directories. 

- `http://localhost/website`
- `http://localhost/blog`

Then you can use the URL Rewrites advanced configuration and map to internal directories in the root as needed. 

```toml
[general]
root = "/var/www/html"

[advanced]

# Website
[[advanced.rewrites]]
source = "/website/{**}"
# it will map to /var/www/html/the-internal-website/...
destination = "/the-internal-website/$1"

# Blog
[[advanced.rewrites]]
source = "/blog/{**}"
# it will map to /var/www/html/the-internal-blog/...
destination = "/the-internal-blog/$1"
```

The advantage of this is that you can use [custom glob patterns and replacements](https://static-web-server.net/features/url-rewrites/#destination) for more advanced path mapping.

**Comment by superwushu** [comment]
Thanks Jose. That works but there is one nit: if I enable directory listing then "/" would also list directories `/website` and `blog`, which is not quite wanted. But that's okay, as the service is beind Nginx proxy in my use case.

My intention was to host the service as if `/base/...` is the only accepted path, and requesting to `/` would yield 404. But now I'm okay with the URL rewrite as a solution when I just realized SWS is just a file server but not a reverse proxy. You may close the issue.

Thanks again for the quick response.

**Comment by joseluisq** [comment]
Ok, I get the idea of not wanting to expose the content of the root dir.
SWS can not do this but I could be easily allowed with a new general option something like this.

Here is some proposal:

```toml
[general]
# Parent root
root = "/var/www/html"
# New option proposal
root-subdirs = true

[advanced]

# Website
[[advanced.rewrites]]
# Requests via http://localhost/... 
source = "{**}"
# ... will be mapped to /var/www/html/the-internal-website/...
destination = "/the-internal-website/$1"
```

**How could it work?**

The boolean `root-subdirs` should be a new option to allow serving files from multiple subdirectories (root subdirs) within the parent root.
If true, then SWS won't serve files directly from the parent root / anymore, making it internal. For example, you won't be able to serve any file from it or list its content directly (parent root level). Instead, you have to use _URL Rewrites_ to specify which subdir(s) to serve. So you can simulate multiple root subdirectories without exposing the content of the parent root.

**Comment by superwushu** [comment]
Thank Jose your proposal looks nice. Just wonder how could a boolean `root-subdirs` identify the root level without extra parameters? E.g. if a rewrite defines `/a/b/c -> /internal/b/c` will this option see `/a` or `/a/b` as the root?

**Comment by joseluisq** [comment]
> Thank Jose your proposal looks nice. Just wonder how could a boolean root-subdirs identify the root level without extra parameters?

It will depend on the `source` pattern of every _Rewrites_ entry.

For example, the above SWS config (`source = "{**}"`) just maps everything in the request path to a single internal directory. In this case, the full system path will always be in the form of `<server_root_path>/the-internal-website/<request_path_here>` (a.k.a root subdir).

On the other hand, if you need multiple root subdirs then you will need more _Rewrites_ entries and tweak their  `source` pattern to match accordingly.

> E.g. if a rewrite defines /a/b/c -> /internal/b/c will this option see /a or /a/b as the root?

What do you mean by this? Can you explain it in more detail or show a SWS config example?

**Comment by joseluisq** [comment]
And for the root subdir (or root subdir level) logic. For example, in case the base path of the `destination` is contained as a prefix of a request path, then we can reply with a 404 because the idea is to show the content of the root subdir (child) but not the root content (parent).

**Comment by valerii15298** [comment]
hello @joseluisq 
I wanna serve my Vitepress static docs but cannot get it working with subpath...
When serving from the root - everything works fine, but when using with subpath nested urls are not found.

With this config:
```toml
[general]
root = "/app"
```
Everything works fine. Then I put subpath like this:
```toml
[general]
root = "/app"

[advanced]

[[advanced.rewrites]]
source = "/docs/{**}"
destination = "/$1"
```
And when requesting `localhost:8080/docs/` - it serves `index.html`, but when requesting `localhost:8080/docs/assets/chunks/theme.CwUdYMJE.js` - I get not found...

My file structure is:

```
/app
  index.html
  assets/
    chunks/
      theme.CwUdYMJE.js
```

**Comment by valerii15298** [comment]
Took me a while to guess it but this is what did work for me:
```toml
[general]
root = "/app"

[advanced]

[[advanced.rewrites]]
source = "/docs/{**}"
destination = "/$1"

[[advanced.rewrites]]
source = "/docs/{**/*}"
destination = "/$1"
```

Basically using both globs `{**}` and `{**/*}`
