### ISSUE TITLE
Docker ARM64 Image

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/static-web-server#54]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**
We would like to be able to use `static-web-server` on ARM 64 Docker environments.

**Describe alternatives you've considered**

Probably we want to revisit https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

**Additional context**
No

**Comment by talesam** [comment]
```
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

I'm running docker-compose on an ARM64 like this:

```
version: "3.9"

services:
  sws-veidahavan:
    image: joseluisq/static-web-server:2
    container_name: sws-veidahavan
    restart: always
    #environment:
      # Nota: esses envs são personalizáveis, mas também opcionais
      #- SERVER_HOST=127.0.0.1
      #- SERVER_PORT=80
      #- SERVER_ROOT=/public
    volumes:
      - /home/tales/Docker/SWS/assets.veidahavan.com/html:/public
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.entryPoints=https"
    #  - "traefik.backend=localhost_dev"
    #  - "traefik.frontend.rule=Host:localhost.dev"
    #  - "traefik.port=80"
    expose:
      - 80
    networks:
      t4l35-net:

networks:
  t4l35-net:
      name: t4l35-net
```

I looked in the documentation and it said that the image is ARM64 compatible, can you help me?
https://sws.joseluisq.net/platforms-architectures/
