### ISSUE TITLE
Show "index of" page

### ISSUE THREAD

**Issue by talesam** [joseluisq/static-web-server#89]
I have version 2, I configured it yesterday on a server and on top it has the nginx proxy manager to pass the ssl domain, but instead of opening the server without the html, a 404 error appears, could you help?

https://repo.biglinux.com.br/
https://iso.biglinux.com.br/

**Comment by joseluisq** [comment]
> but instead of opening the server without the html, a 404 error appears, could you help?

Please can you clarify that. I didn't get what you would like with.

**Comment by joseluisq** [comment]
Maybe what do you mean is how you can show your website (root dir /) which doesn't have an `index.html`?
If so then what you could want is [listing the content of a directory](https://sws.joseluisq.net/features/directory-listing/).

**Comment by talesam** [comment]
I'm running your server on a docker, now on an x86 with the following docker-compose:

```
version: "3.9"

services:
  sws-bigrepo:
    image: joseluisq/static-web-server:2
    container_name: sws-bigrepo
    restart: always
    #environment:
      # Nota: esses envs são personalizáveis, mas também opcionais
      #- SERVER_HOST=127.0.0.1
      #- SERVER_PORT=80
      #- SERVER_ROOT=/public
    volumes:
      - /home/ubuntu/Docker/SWS/big-repo/html:/public
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.frontend.entryPoints=https"
    #  - "traefik.backend=localhost_dev"
    #  - "traefik.frontend.rule=Host:localhost.dev"
    #  - "traefik.port=80"
    expose:
      - 80
    networks:
      big-net:

networks:
  big-net:
      name: big-net
```
I'm exposing port 80 that is "taken" by Nginx Proxy manager (https://nginxproxymanager.com/), it plays the role of the reverse proxy and where I configure SSL.

So when I go up the server with the domain, it gives me a 404, but I want it to display the files inside the "html" folder without me having to put an index.html file, because this will be a package repository, I'm migrating the nginx to your server.

See: https://build.biglinux.com.br/x86_64/

I want it to display only the files, but it's giving 404 if I don't put a .html file to display something.
